[package]
name = "tablenest"
version = "0.0.1"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
read-from = "0.5.2"
rfd = "0.15.2"
walkdir = "2.5.0"

[dev-dependencies]
sha256 = "1.5.0"
tempfile = "3.8"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 3
